type Event {
  id: String
  name: String
  description: String
  state: Int
  place: String
  organizer: String
  startDate: String
  endDate: String
  created_at: String
  medias: String
  participants: [Participant]
}
type Participant {
  firstname: String
  lastname: String
}
input ParticipantInput {
  firstname: String
  lastname: String
}
type User {
  name: String
}
input EventInput {
  id: String
  name: String
  description: String
  state: Int
  place: String
  organizer: String
  startDate: String
  endDate: String
  created_at: String
  medias: Upload
  participants: [ParticipantInput]
}
type Allo {
  id: String
  name: String
  available: Boolean
  description: String
  mediaId: String
  phone: String
  options: [Option]
}
type Option {
  name: String
  id: String
  allo_id: String
}
type Query {
  hello: String
  getDisplayedEvent: [Event]
  getAllos: [Allo]
  getAllAllos: [Allo]
  getCommandes: [Commande]
}
type Commande {
  id: String
  firstname: String
  lastname: String
  mail: String
  place: String
  allo: Allo
  status: Int
  option: String
  createdAt: String
}
input OptionInput {
  name: String
  id: String
  allo_id: String
}
input CommandeInput2 {
  id: String
  firstname: String
  lastname: String
  mail: String
  place: String
  allo: AlloInput
  status: Int
  option: String
  createdAt: String
}
input AlloInput {
  name: String
  description: String
  available: Boolean
  image: Upload
  id: String
  mediaId: String
  phone: String
  options: [String]
}
input AlloInput2 {
  name: String
  description: String
  available: Boolean
  image: Upload
  id: String
  mediaId: String
  phone: String
  options: [OptionInput]
}
input CommandeInput {
  allo: AlloInput2
  person: PersonInput
}
input PersonInput {
  firstname: String
  lastname: String
  mail: String
  place: String
  option: String
}
type Mutation {
  login(login: String!, password: String!): User
  saveEvents(events: [EventInput]!): Boolean
  addEvent(event: EventInput!): String
  updateEvent(event: EventInput!): Boolean
  updateAllo(allo: AlloInput): Boolean
  createAllo(allo: AlloInput!): String
  sendMail(person: PersonInput!, eventId: String!): String
  validateCode(codeInput: String, eventId: String!, userId: String!): Boolean
  commander(command: CommandeInput): Boolean
  setLivre(commandId: String): Boolean
  sendMailCommand(command: CommandeInput2): Boolean
}
